local File = require('vgit.core.File')

local eq = assert.are.same

describe('File:', function()
  local tmp_file = '/tmp/vgit_file_test_' .. os.time() .. '.txt'

  after_each(function()
    os.remove(tmp_file)
  end)

  describe('constructor', function()
    it('should store path', function()
      local file = File('/path/to/file.txt')
      eq(file._path, '/path/to/file.txt')
    end)

    it('should initialize fd to nil', function()
      local file = File('/path/to/file.txt')
      eq(file._fd, nil)
    end)
  end)

  describe('open', function()
    it('should open file and return true', function()
      local file = File(tmp_file)
      local result = file:open('wb')
      eq(result, true)
      assert.is_not_nil(file._fd)
      file:close()
    end)

    it('should default to append binary mode', function()
      local file = File(tmp_file)
      file:open()
      file:write({ 'test' })
      file:close()
      file:open()
      file:write({ 'test2' })
      file:close()

      local f = io.open(tmp_file, 'rb')
      local content = f:read('*a')
      f:close()
      eq(content, 'test\ntest2\n')
    end)

    it('should close existing fd before opening', function()
      local file = File(tmp_file)
      file:open('wb')
      local old_fd = file._fd
      file:open('wb')
      assert.is_not_nil(file._fd)
      assert.is_not_equal(old_fd, file._fd)
      file:close()
    end)

    it('should return false if file cannot be opened', function()
      local file = File('/nonexistent/path/to/file.txt')
      local result = file:open('r')
      eq(result, false)
      eq(file._fd, nil)
    end)
  end)

  describe('write', function()
    it('should write lines to file', function()
      local file = File(tmp_file)
      file:open('wb')
      file:write({ 'line1', 'line2', 'line3' })
      file:close()

      local f = io.open(tmp_file, 'rb')
      local content = f:read('*a')
      f:close()
      eq(content, 'line1\nline2\nline3\n')
    end)

    it('should flush after writing', function()
      local file = File(tmp_file)
      file:open('wb')
      file:write({ 'test' })

      local f = io.open(tmp_file, 'rb')
      local content = f:read('*a')
      f:close()
      eq(content, 'test\n')
      file:close()
    end)

    it('should return true on success', function()
      local file = File(tmp_file)
      file:open('wb')
      local result = file:write({ 'test' })
      eq(result, true)
      file:close()
    end)

    it('should return nil and error if file not open', function()
      local file = File(tmp_file)
      local result, err = file:write({ 'test' })
      eq(result, nil)
      eq(err, 'file not open')
    end)

    it('should handle empty lines table', function()
      local file = File(tmp_file)
      file:open('wb')
      local result = file:write({})
      eq(result, true)
      file:close()

      local f = io.open(tmp_file, 'rb')
      local content = f:read('*a')
      f:close()
      eq(content, '')
    end)
  end)

  describe('append', function()
    it('should open file if not open', function()
      local file = File(tmp_file)
      local result = file:append({ 'line1' })
      eq(result, true)
      assert.is_not_nil(file._fd)
      file:close()
    end)

    it('should write to existing open file', function()
      local file = File(tmp_file)
      file:open('wb')
      file:append({ 'line1' })
      file:append({ 'line2' })
      file:close()

      local f = io.open(tmp_file, 'rb')
      local content = f:read('*a')
      f:close()
      eq(content, 'line1\nline2\n')
    end)

    it('should return error if cannot open file', function()
      local file = File('/nonexistent/path/to/file.txt')
      local result, err = file:append({ 'test' })
      eq(result, nil)
      eq(err, 'could not open file')
    end)
  end)

  describe('close', function()
    it('should close open file', function()
      local file = File(tmp_file)
      file:open('wb')
      assert.is_not_nil(file._fd)
      file:close()
      eq(file._fd, nil)
    end)

    it('should be safe to call on unopened file', function()
      local file = File(tmp_file)
      file:close()
      eq(file._fd, nil)
    end)

    it('should be safe to call multiple times', function()
      local file = File(tmp_file)
      file:open('wb')
      file:close()
      file:close()
      eq(file._fd, nil)
    end)
  end)

  describe('is_open', function()
    it('should return false before opening', function()
      local file = File(tmp_file)
      eq(file:is_open(), false)
    end)

    it('should return true after opening', function()
      local file = File(tmp_file)
      file:open('wb')
      eq(file:is_open(), true)
      file:close()
    end)

    it('should return false after closing', function()
      local file = File(tmp_file)
      file:open('wb')
      file:close()
      eq(file:is_open(), false)
    end)
  end)

  describe('remove', function()
    it('should remove file and return true', function()
      local file = File(tmp_file)
      file:open('wb')
      file:write({ 'test' })
      file:close()

      local result = file:remove()
      eq(result, true)

      local f = io.open(tmp_file, 'r')
      eq(f, nil)
    end)

    it('should close file before removing', function()
      local file = File(tmp_file)
      file:open('wb')
      file:write({ 'test' })

      file:remove()
      eq(file._fd, nil)
    end)

    it('should be safe to call on nonexistent file', function()
      local file = File('/nonexistent/path/to/file.txt')
      local result = file:remove()
      eq(result, nil)
    end)
  end)
end)
