local WindowHandle = require('vgit.ui.window.WindowHandle')

describe('WindowHandle:', function()
  describe('Abstract interface', function()
    it('should throw error when calling open on base class', function()
      local handle = WindowHandle()
      assert.has_error(function()
        handle:open()
      end, 'WindowHandle:open() must be implemented by subclass')
    end)

    it('should throw error when calling close on base class', function()
      local handle = WindowHandle()
      assert.has_error(function()
        handle:close()
      end, 'WindowHandle:close() must be implemented by subclass')
    end)

    it('should throw error when calling is_valid on base class', function()
      local handle = WindowHandle()
      assert.has_error(function()
        handle:is_valid()
      end, 'WindowHandle:is_valid() must be implemented by subclass')
    end)

    it('should throw error when calling get_width on base class', function()
      local handle = WindowHandle()
      assert.has_error(function()
        handle:get_width()
      end, 'WindowHandle:get_width() must be implemented by subclass')
    end)

    it('should throw error when calling set_option on base class', function()
      local handle = WindowHandle()
      assert.has_error(function()
        handle:set_option('test', 'value')
      end, 'WindowHandle:set_option() must be implemented by subclass')
    end)
  end)

  describe('Extension', function()
    it('should be extendable by subclasses', function()
      local CustomHandle = WindowHandle:extend()
      function CustomHandle:open()
        return 'custom_open'
      end

      local handle = CustomHandle()
      assert.are.equal('custom_open', handle:open())
    end)
  end)
end)
