local parser = require('vgit.cli.parser')

describe('CLI Parser', function()
  describe('parse', function()
    it('should parse simple diff command', function()
      local result = parser.parse({ 'diff' })
      assert.are.same('diff', result.command)
      assert.are.same({}, result.files)
      assert.are.same({}, result.commits)
    end)

    it('should parse diff with --cached flag', function()
      local result = parser.parse({ 'diff', '--cached' })
      assert.are.same('diff', result.command)
      assert.is_true(result.options.cached)
    end)

    it('should parse diff with --staged flag', function()
      local result = parser.parse({ 'diff', '--staged' })
      assert.are.same('diff', result.command)
      assert.is_true(result.options.staged)
    end)

    it('should parse diff with --lens flag', function()
      local result = parser.parse({ 'diff', '--lens' })
      assert.are.same('diff', result.command)
      assert.is_true(result.options.lens)
    end)

    it('should parse diff with --split flag', function()
      local result = parser.parse({ 'diff', '--split' })
      assert.are.same('diff', result.command)
      assert.is_true(result.options.split)
    end)

    it('should parse diff with --unified flag', function()
      local result = parser.parse({ 'diff', '--unified_view' })
      assert.are.same('diff', result.command)
      assert.is_true(result.options.unified_view)
    end)

    it('should parse diff with file path', function()
      local result = parser.parse({ 'diff', 'path/to/file.lua' })
      assert.are.same('diff', result.command)
      assert.are.same(1, #result.files)
      assert.are.same('path/to/file.lua', result.files[1])
      assert.are.same('path/to/file.lua', result.file_path) -- backward compat
    end)

    it('should parse diff with multiple flags', function()
      local result = parser.parse({ 'diff', '--cached', '--split', 'file.lua' })
      assert.are.same('diff', result.command)
      assert.is_true(result.options.cached)
      assert.is_true(result.options.split)
      assert.are.same('file.lua', result.files[1])
    end)

    it('should parse diff with --buffer flag', function()
      local result = parser.parse({ 'diff', '--buffer' })
      assert.are.same('diff', result.command)
      assert.are.same(0, result.options.buffer) -- default to current buffer
    end)

    it('should parse diff with --buffer=N', function()
      local result = parser.parse({ 'diff', '--buffer=5' })
      assert.are.same('diff', result.command)
      assert.are.same(5, result.options.buffer)
    end)

    it('should parse blame command', function()
      local result = parser.parse({ 'blame' })
      assert.are.same('blame', result.command)
    end)

    it('should parse blame with --line option', function()
      local result = parser.parse({ 'blame', '--line=42' })
      assert.are.same('blame', result.command)
      assert.are.same(42, result.options.line)
    end)

    it('should handle empty args', function()
      local result = parser.parse({})
      assert.is_nil(result.command)
      assert.are.same({}, result.files)
    end)
  end)

  describe('validate', function()
    it('should accept valid diff command', function()
      local parsed = parser.parse({ 'diff', '--cached' })
      local valid, err = parser.validate(parsed)
      assert.is_true(valid)
      assert.is_nil(err)
    end)

    it('should reject both --lens and --screen', function()
      local parsed = parser.parse({ 'diff', '--lens', '--screen' })
      local valid, err = parser.validate(parsed)
      assert.is_false(valid)
      assert.is_not_nil(err)
    end)

    it('should reject both --split and --unified', function()
      local parsed = parser.parse({ 'diff', '--split', '--unified_view' })
      local valid, err = parser.validate(parsed)
      assert.is_false(valid)
      assert.is_not_nil(err)
    end)

    it('should accept empty command', function()
      local parsed = parser.parse({})
      local valid, err = parser.validate(parsed)
      assert.is_true(valid)
    end)
  end)

  describe('backward compatibility', function()
    it('should set file_path from files[1]', function()
      local result = parser.parse({ 'diff', 'myfile.lua' })
      assert.are.same('myfile.lua', result.file_path)
      assert.are.same('myfile.lua', result.files[1])
    end)

    it('should set flags from options', function()
      local result = parser.parse({ 'diff', '--cached' })
      assert.are.same(result.options, result.flags)
    end)
  end)
end)
