local diff_command = require('vgit.cli.commands.diff')

local eq = assert.are.same

describe('diff_command:', function()
  describe('empty args', function()
    it('should return default opts with empty args', function()
      local opts = diff_command.parse_args({})
      eq({}, opts.files)
      eq({}, opts.refs)
      assert.is_false(opts.staged)
      assert.is_nil(opts.buffer_num)
      eq({}, opts.flags)
      eq({}, opts.ambiguous)
      assert.is_false(opts.explicit_files)
    end)
  end)

  describe('--staged and --cached', function()
    it('should set staged for --staged', function()
      local opts = diff_command.parse_args({ '--staged' })
      assert.is_true(opts.staged)
    end)

    it('should set staged for --cached', function()
      local opts = diff_command.parse_args({ '--cached' })
      assert.is_true(opts.staged)
    end)
  end)

  describe('--buffer', function()
    it('should set buffer_num to 0 for --buffer', function()
      local opts = diff_command.parse_args({ '--buffer' })
      assert.are.equal(0, opts.buffer_num)
    end)

    it('should parse --buffer=N', function()
      local opts = diff_command.parse_args({ '--buffer=5' })
      assert.are.equal(5, opts.buffer_num)
    end)

    it('should default to 0 for invalid --buffer=X', function()
      local opts = diff_command.parse_args({ '--buffer=abc' })
      assert.are.equal(0, opts.buffer_num)
    end)
  end)

  describe('-- separator', function()
    it('should treat everything after -- as files', function()
      local opts = diff_command.parse_args({ 'HEAD', '--', 'file1.lua', 'file2.lua' })
      eq({ 'file1.lua', 'file2.lua' }, opts.files)
      assert.is_true(opts.explicit_files)
      eq({ 'HEAD' }, opts.refs)
    end)

    it('should handle -- with no following args', function()
      local opts = diff_command.parse_args({ '--' })
      eq({}, opts.files)
      assert.is_true(opts.explicit_files)
    end)
  end)

  describe('flags', function()
    it('should collect long flags', function()
      local opts = diff_command.parse_args({ '--word-diff', '--stat' })
      eq({ '--word-diff', '--stat' }, opts.flags)
    end)

    it('should collect short flags', function()
      local opts = diff_command.parse_args({ '-w', '-p' })
      eq({ '-w', '-p' }, opts.flags)
    end)
  end)

  describe('ref detection', function()
    it('should detect HEAD as ref', function()
      local opts = diff_command.parse_args({ 'HEAD' })
      eq({ 'HEAD' }, opts.refs)
    end)

    it('should detect HEAD~1 as ref', function()
      local opts = diff_command.parse_args({ 'HEAD~1' })
      eq({ 'HEAD~1' }, opts.refs)
    end)

    it('should detect HEAD^ as ref', function()
      local opts = diff_command.parse_args({ 'HEAD^' })
      eq({ 'HEAD^' }, opts.refs)
    end)

    it('should detect @ as ref', function()
      local opts = diff_command.parse_args({ '@' })
      eq({ '@' }, opts.refs)
    end)

    it('should detect double-dot range as ref', function()
      local opts = diff_command.parse_args({ 'HEAD~2..HEAD' })
      eq({ 'HEAD~2..HEAD' }, opts.refs)
    end)

    it('should detect triple-dot range as ref', function()
      local opts = diff_command.parse_args({ 'main...feature' })
      eq({ 'main...feature' }, opts.refs)
    end)

    it('should detect commit hash (7 chars) as ref', function()
      local opts = diff_command.parse_args({ 'abc1234' })
      eq({ 'abc1234' }, opts.refs)
    end)

    it('should detect full commit hash (40 chars) as ref', function()
      local hash = 'abcdef1234567890abcdef1234567890abcdef12'
      local opts = diff_command.parse_args({ hash })
      eq({ hash }, opts.refs)
    end)

    it('should detect origin/main as remote ref', function()
      local opts = diff_command.parse_args({ 'origin/main' })
      eq({ 'origin/main' }, opts.refs)
    end)

    it('should detect upstream/feature as remote ref', function()
      local opts = diff_command.parse_args({ 'upstream/feature' })
      eq({ 'upstream/feature' }, opts.refs)
    end)
  end)

  describe('file detection', function()
    it('should detect file with extension as file', function()
      local opts = diff_command.parse_args({ 'file.lua' })
      eq({ 'file.lua' }, opts.files)
    end)

    it('should detect path with directory as file', function()
      local opts = diff_command.parse_args({ 'src/components/file.lua' })
      eq({ 'src/components/file.lua' }, opts.files)
    end)

    it('should detect file with spaces/special chars as file', function()
      local opts = diff_command.parse_args({ 'my file.txt' })
      eq({ 'my file.txt' }, opts.files)
    end)
  end)

  describe('ambiguous args', function()
    it('should mark single word without extension as ambiguous', function()
      local opts = diff_command.parse_args({ 'main' })
      eq({ 'main' }, opts.ambiguous)
    end)

    it('should mark multiple ambiguous args', function()
      local opts = diff_command.parse_args({ 'main', 'feature' })
      eq({ 'main', 'feature' }, opts.ambiguous)
    end)

    it('should not treat Makefile-style names as refs', function()
      local opts = diff_command.parse_args({ 'Makefile' })
      eq({ 'Makefile' }, opts.ambiguous)
    end)
  end)

  describe('mixed args', function()
    it('should correctly classify mixed arguments', function()
      local opts = diff_command.parse_args({ 'HEAD~1', '--staged', 'src/file.lua' })
      eq({ 'HEAD~1' }, opts.refs)
      assert.is_true(opts.staged)
      eq({ 'src/file.lua' }, opts.files)
    end)

    it('should handle two refs', function()
      local opts = diff_command.parse_args({ 'HEAD~2', 'HEAD' })
      eq({ 'HEAD~2', 'HEAD' }, opts.refs)
    end)

    it('should handle ref with file after --', function()
      local opts = diff_command.parse_args({ 'HEAD', '--', 'path/to/file.lua' })
      eq({ 'HEAD' }, opts.refs)
      eq({ 'path/to/file.lua' }, opts.files)
      assert.is_true(opts.explicit_files)
    end)
  end)
end)
