local LogFormatter = require('vgit.core.console.LogFormatter')

local eq = assert.are.same

describe('LogFormatter:', function()
  describe('clean', function()
    it('should return string as-is', function()
      eq(LogFormatter.clean('hello'), 'hello')
    end)

    it('should return single-item table as string', function()
      eq(LogFormatter.clean({ 'hello' }), 'hello')
    end)

    it('should return multi-item table as table', function()
      eq(LogFormatter.clean({ 'hello', 'world' }), { 'hello', 'world' })
    end)

    it('should return empty string for empty table', function()
      eq(LogFormatter.clean({}), '')
    end)

    it('should return empty string for non-string, non-table', function()
      eq(LogFormatter.clean(123), '')
    end)

    it('should return empty string for table with non-contiguous keys', function()
      eq(LogFormatter.clean({ 'valid', nil, 'also valid' }), '')
    end)

    it('should return empty string for table with only non-string items', function()
      eq(LogFormatter.clean({ 1, 2, true, {} }), '')
    end)
  end)

  describe('constructor', function()
    it('should accept a string message', function()
      local formatter = LogFormatter('Hello world')
      eq(formatter._msg, 'Hello world')
      assert.is_false(formatter._is_formatted)
    end)

    it('should accept a single-item table', function()
      local formatter = LogFormatter({ 'Single line' })
      eq(formatter._msg, 'Single line')
    end)

    it('should accept a multi-item table', function()
      local formatter = LogFormatter({ 'Line 1', 'Line 2', 'Line 3' })
      eq(formatter._msg, { 'Line 1', 'Line 2', 'Line 3' })
    end)

    it('should handle empty string', function()
      local formatter = LogFormatter('')
      eq(formatter._msg, '')
    end)

    it('should handle empty table', function()
      local formatter = LogFormatter({})
      eq(formatter._msg, '')
    end)

    it('should handle non-string, non-table input as empty', function()
      local formatter = LogFormatter(123)
      eq(formatter._msg, '')
    end)

    it('should handle nil input', function()
      local formatter = LogFormatter(nil)
      eq(formatter._msg, '')
    end)

    it('should default timestamp to true', function()
      local formatter = LogFormatter('test')
      eq(formatter._should_show_timestamp, true)
    end)

    it('should default timestamp to true when opts is empty table', function()
      local formatter = LogFormatter('test', {})
      eq(formatter._should_show_timestamp, true)
    end)

    it('should set timestamp to false when explicitly disabled', function()
      local formatter = LogFormatter('test', { timestamp = false })
      eq(formatter._should_show_timestamp, false)
    end)

    it('should set timestamp to true when explicitly enabled', function()
      local formatter = LogFormatter('test', { timestamp = true })
      eq(formatter._should_show_timestamp, true)
    end)
  end)

  describe('add_prefix', function()
    it('should include VGIT prefix', function()
      local formatter = LogFormatter('test')
      local result = formatter:add_prefix('message', 'info')
      assert.is_true(result:match('^%[VGit%]') ~= nil)
    end)

    it('should include log type when provided', function()
      local formatter = LogFormatter('test')
      local result = formatter:add_prefix('message', 'info')
      assert.is_true(result:match('%[INFO%]') ~= nil)
    end)

    it('should uppercase log type', function()
      local formatter = LogFormatter('test')
      local result = formatter:add_prefix('message', 'info')
      assert.is_true(result:match('%[INFO%]') ~= nil)
      assert.is_nil(result:match('%[info%]'))
    end)

    it('should include timestamp when enabled', function()
      local formatter = LogFormatter('test', { timestamp = true })
      local result = formatter:add_prefix('message', 'info')
      assert.is_true(result:match('%[%d%d:%d%d:%d%d%]') ~= nil)
    end)

    it('should not include timestamp when disabled', function()
      local formatter = LogFormatter('test', { timestamp = false })
      local result = formatter:add_prefix('message', 'info')
      assert.is_nil(result:match('%[%d%d:%d%d:%d%d%]'))
    end)

    it('should include fn_source when provided', function()
      local formatter = LogFormatter('test')
      local result = formatter:add_prefix('message', 'info', '@file.lua')
      assert.is_true(result:match('%[@file%.lua%]') ~= nil)
    end)

    it('should include fn_name when provided', function()
      local formatter = LogFormatter('test')
      local result = formatter:add_prefix('message', 'info', '@file.lua', 'func')
      assert.is_true(result:match('%[@file%.lua%]') ~= nil)
      assert.is_true(result:match('%[func%]') ~= nil)
    end)

    it('should not include fn_source or fn_name when not provided', function()
      local formatter = LogFormatter('test')
      local result = formatter:add_prefix('message', 'info')
      assert.is_nil(result:match('%[@'))
      assert.is_nil(result:match('%[func'))
    end)

    it('should throw error when fn_source is not a string', function()
      local formatter = LogFormatter('test')
      assert.has_error(function()
        formatter:add_prefix('message', 'info', 123)
      end)
    end)

    it('should throw error when fn_name is not a string', function()
      local formatter = LogFormatter('test')
      assert.has_error(function()
        formatter:add_prefix('message', 'info', '@file.lua', 123)
      end)
    end)

    it('should handle empty message', function()
      local formatter = LogFormatter('test')
      local result = formatter:add_prefix('', 'info')
      assert.is_true(result:match('^%[VGit%]') ~= nil)
    end)

    it('should handle nil log_type', function()
      local formatter = LogFormatter('test')
      local result = formatter:add_prefix('message', nil)
      assert.is_true(result:match('^%[VGit%]') ~= nil)
      assert.is_nil(result:match('%[INFO%]'))
    end)
  end)

  describe('add_indentation', function()
    it('should add 7-space indentation', function()
      local formatter = LogFormatter('test')
      local result = formatter:add_indentation('message')
      eq(result, '       message')
    end)

    it('should throw error for non-string input', function()
      local formatter = LogFormatter('test')
      assert.has_error(function()
        formatter:add_indentation(123)
      end)
    end)

    it('should handle empty string', function()
      local formatter = LogFormatter('test')
      local result = formatter:add_indentation('')
      eq(result, '       ')
    end)
  end)

  describe('format', function()
    it('should format string message with prefix', function()
      local formatter = LogFormatter('Test message')
      formatter:format('info')
      local result = formatter:value()
      assert.is_true(result:match('^%[VGit%]') ~= nil)
      assert.is_true(result:match('Test message') ~= nil)
    end)

    it('should accept nil log_type', function()
      local formatter = LogFormatter('Test message')
      formatter:format(nil)
      local result = formatter:value()
      assert.is_true(result:match('^%[VGit%]') ~= nil)
      assert.is_nil(result:match('%[INFO%]'))
    end)

    it('should throw error when log_type is not a string', function()
      local formatter = LogFormatter('Test')
      assert.has_error(function()
        formatter:format(123)
      end)
    end)

    it('should not re-format if already formatted', function()
      local formatter = LogFormatter('Test')
      formatter:format('info')
      local first = formatter:value()
      formatter:format('error')
      local second = formatter:value()
      eq(first, second)
    end)

    it('should format multi-line message with prefix on first line', function()
      local formatter = LogFormatter({ 'First', 'Second', 'Third' })
      formatter:format('debug')
      local result = formatter:value()
      assert.is_true(result:match('^%[VGit%]') ~= nil)
      assert.is_true(result:match('First') ~= nil)
      assert.is_true(result:match('Second') ~= nil)
    end)

    it('should format two-line message with indentation on second line', function()
      local formatter = LogFormatter({ 'First', 'Second' })
      formatter:format('info')
      local result = formatter:value()
      assert.is_true(result:match('First') ~= nil)
      assert.is_true(result:match('       Second') ~= nil)
    end)

    it('should format empty string message', function()
      local formatter = LogFormatter('')
      formatter:format('info')
      local result = formatter:value()
      assert.is_true(result:match('^%[VGit%]') ~= nil)
    end)

    it('should include fn_source and fn_name when provided', function()
      local formatter = LogFormatter('Test')
      formatter:format('info', '@file.lua', 'my_func')
      local result = formatter:value()
      assert.is_true(result:match('%[@file%.lua%]') ~= nil)
      assert.is_true(result:match('%[my_func%]') ~= nil)
    end)
  end)

  describe('value', function()
    it('should return unformatted message initially', function()
      local formatter = LogFormatter('Test')
      eq(formatter:value(), 'Test')
    end)

    it('should return empty string for nil input', function()
      local formatter = LogFormatter(nil)
      eq(formatter:value(), '')
    end)

    it('should return formatted message after formatting', function()
      local formatter = LogFormatter('Test message')
      formatter:format('info')
      local result = formatter:value()
      assert.is_true(#result > 0)
    end)
  end)

  describe('chaining', function()
    it('should return self from format', function()
      local formatter = LogFormatter('Test')
      local result = formatter:format('info')
      eq(result, formatter)
    end)
  end)
end)
