local test_harness = require('ops.lib.test_harness')
local GitQueryBuilder = require('vgit.git.GitQueryBuilder')

local describe = test_harness.describe
local it = test_harness.it

describe('GitQueryBuilder Validation', function()
  local repo = '/path/to/repo'

  describe('constructor validation', function()
    it('should error with nil repository', function()
      local success = pcall(function()
        GitQueryBuilder(nil)
      end)
      assert(not success, 'should reject nil repository')
    end)

    it('should error with non-string repository', function()
      local success = pcall(function()
        GitQueryBuilder(123)
      end)
      assert(not success, 'should reject number as repository')
    end)

    it('should error with empty string repository', function()
      local success = pcall(function()
        GitQueryBuilder('')
      end)
      assert(not success, 'should reject empty repository')
    end)

    it('should error with whitespace-only repository', function()
      local success = pcall(function()
        GitQueryBuilder('   ')
      end)
      assert(not success, 'should reject whitespace repository')
    end)
  end)

  describe('command method validation', function()
    it('should prevent calling multiple command methods', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():show()
      end)
      assert(not success, 'should reject multiple commands')
    end)

    it('should error on paginate without command', function()
      local success = pcall(function()
        GitQueryBuilder(repo):paginate(50, 0)
      end)
      assert(not success, 'should require command first')
    end)

    it('should error on file without command', function()
      local success = pcall(function()
        GitQueryBuilder(repo):file('test.lua')
      end)
      assert(not success, 'should require command first')
    end)
  end)

  describe('pagination validation', function()
    it('should error when paginating non-paginated command', function()
      local success = pcall(function()
        GitQueryBuilder(repo):status():paginate(50, 0)
      end)
      assert(not success, 'should reject pagination for status')
    end)

    it('should error when paginating diff command', function()
      local success = pcall(function()
        GitQueryBuilder(repo):diff():limit(50)
      end)
      assert(not success, 'should reject pagination for diff')
    end)

    it('should error with non-number count', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():limit('50')
      end)
      assert(not success, 'should reject string as count')
    end)

    it('should error with zero count', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():limit(0)
      end)
      assert(not success, 'should reject zero count')
    end)

    it('should error with negative count', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():limit(-10)
      end)
      assert(not success, 'should reject negative count')
    end)

    it('should error with non-number offset', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():skip('100')
      end)
      assert(not success, 'should reject string as offset')
    end)

    it('should error with negative offset', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():skip(-10)
      end)
      assert(not success, 'should reject negative offset')
    end)

    it('should error on duplicate pagination calls', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():limit(50):skip(100)
      end)
      assert(not success, 'should reject calling both limit and skip separately')
    end)

    it('should error on calling paginate after limit', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():limit(50):paginate(100, 0)
      end)
      assert(not success, 'should reject paginate after limit')
    end)
  end)

  describe('file validation', function()
    it('should error when adding files to diff-tree', function()
      local success = pcall(function()
        GitQueryBuilder(repo):diff_tree():file('test.lua')
      end)
      assert(not success, 'should reject file for diff-tree')
    end)

    it('should error with non-string filename', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():file(123)
      end)
      assert(not success, 'should reject number as filename')
    end)

    it('should error with empty string filename', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():file('')
      end)
      assert(not success, 'should reject empty filename')
    end)

    it('should error with whitespace-only filename', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():file('   ')
      end)
      assert(not success, 'should reject whitespace filename')
    end)

    it('should error on calling files without arguments', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():files()
      end)
      assert(not success, 'should require at least one file')
    end)

    it('should error on calling file twice', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():file('a.lua'):file('b.lua')
      end)
      assert(not success, 'should reject duplicate file calls')
    end)

    it('should error on calling files after file', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():file('a.lua'):files('b.lua', 'c.lua')
      end)
      assert(not success, 'should reject files after file')
    end)

    it('should error with invalid file in files array', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():files('valid.lua', 123, 'other.lua')
      end)
      assert(not success, 'should reject non-string in files')
    end)
  end)

  describe('ref validation', function()
    it('should error when adding ref to status', function()
      local success = pcall(function()
        GitQueryBuilder(repo):status():ref('HEAD')
      end)
      assert(not success, 'should reject ref for status')
    end)

    it('should error when adding ref to log', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():ref('HEAD')
      end)
      assert(not success, 'should reject ref for log')
    end)

    it('should error with non-string ref', function()
      local success = pcall(function()
        GitQueryBuilder(repo):show():ref(123)
      end)
      assert(not success, 'should reject number as ref')
    end)

    it('should error with empty string ref', function()
      local success = pcall(function()
        GitQueryBuilder(repo):diff():ref('')
      end)
      assert(not success, 'should reject empty ref')
    end)

    it('should error on calling refs without arguments', function()
      local success = pcall(function()
        GitQueryBuilder(repo):diff():refs()
      end)
      assert(not success, 'should require at least one ref')
    end)

    it('should error with invalid ref in refs array', function()
      local success = pcall(function()
        GitQueryBuilder(repo):diff():refs('HEAD', nil, 'HEAD~1')
      end)
      assert(not success, 'should handle nil in refs')
    end)
  end)

  describe('command-specific validation', function()
    it('should error on staged() for non-diff command', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():staged()
      end)
      assert(not success, 'should reject staged for log')
    end)

    it('should error on cached() for non-diff command', function()
      local success = pcall(function()
        GitQueryBuilder(repo):show():cached()
      end)
      assert(not success, 'should reject cached for show')
    end)

    it('should error on no_patch() for non-show command', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():no_patch()
      end)
      assert(not success, 'should reject no_patch for log')
    end)

    it('should error on unified() for non-diff command', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():unified(5)
      end)
      assert(not success, 'should reject unified for log')
    end)

    it('should error with non-number unified lines', function()
      local success = pcall(function()
        GitQueryBuilder(repo):diff():unified('5')
      end)
      assert(not success, 'should reject string as unified lines')
    end)

    it('should error with negative unified lines', function()
      local success = pcall(function()
        GitQueryBuilder(repo):diff():unified(-1)
      end)
      assert(not success, 'should reject negative unified lines')
    end)

    it('should error on subcommand() for non-stash command', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():subcommand('list')
      end)
      assert(not success, 'should reject subcommand for log')
    end)

    it('should error with invalid stash subcommand', function()
      local success = pcall(function()
        GitQueryBuilder(repo):stash():subcommand('invalid')
      end)
      assert(not success, 'should reject invalid stash subcommand')
    end)

    it('should error with non-string subcommand', function()
      local success = pcall(function()
        GitQueryBuilder(repo):stash():subcommand(123)
      end)
      assert(not success, 'should reject number as subcommand')
    end)
  end)

  describe('option validation', function()
    it('should error with non-string option key', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():option(123, 'value')
      end)
      assert(not success, 'should reject number as option key')
    end)

    it('should error with empty option key', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():option('', 'value')
      end)
      assert(not success, 'should reject empty option key')
    end)

    it('should error with invalid option value type', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():option('author', {})
      end)
      assert(not success, 'should reject table as option value')
    end)
  end)

  describe('format validation', function()
    it('should error with non-string format', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():format(123)
      end)
      assert(not success, 'should reject number as format')
    end)

    it('should error with empty format string', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():format('')
      end)
      assert(not success, 'should reject empty format')
    end)

    it('should error with non-string pretty format', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():pretty(nil)
      end)
      assert(not success, 'should reject nil as pretty format')
    end)
  end)

  describe('raw_args validation', function()
    it('should error on raw_arg without command', function()
      local success = pcall(function()
        GitQueryBuilder(repo):raw_arg('--oneline')
      end)
      assert(not success, 'should require command first')
    end)

    it('should error on raw_args without arguments', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():raw_args()
      end)
      assert(not success, 'should require at least one arg')
    end)

    it('should error with non-string raw_arg', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():raw_arg(123)
      end)
      assert(not success, 'should reject number as raw_arg')
    end)

    it('should error with empty raw_arg', function()
      local success = pcall(function()
        GitQueryBuilder(repo):log():raw_arg('')
      end)
      assert(not success, 'should reject empty raw_arg')
    end)
  end)

  describe('execution validation', function()
    it('should error on to_args without command', function()
      local success = pcall(function()
        GitQueryBuilder(repo):to_args()
      end)
      assert(not success, 'should require command')
    end)

    it('should error on to_command without command', function()
      local success = pcall(function()
        GitQueryBuilder(repo):to_command()
      end)
      assert(not success, 'should require command')
    end)

    it('should error on clone without command', function()
      local success = pcall(function()
        GitQueryBuilder(repo):clone()
      end)
      assert(not success, 'should require command')
    end)
  end)

  describe('query-specific validation', function()
    it('should error on blame without file', function()
      local success = pcall(function()
        GitQueryBuilder(repo):blame():execute()
      end)
      assert(not success, 'should require file for blame')
    end)

    it('should error on diff-tree without refs', function()
      local success = pcall(function()
        GitQueryBuilder(repo):diff_tree():execute()
      end)
      assert(not success, 'should require refs for diff-tree')
    end)

    it('should allow blame with file', function()
      local qb = GitQueryBuilder(repo):blame():file('test.lua')
      local cmd = qb:to_command()
      assert(cmd:match('blame'), 'should build valid blame command')
    end)

    it('should allow diff-tree with refs', function()
      local qb = GitQueryBuilder(repo):diff_tree():refs('HEAD', 'HEAD~1')
      local cmd = qb:to_command()
      assert(cmd:match('diff%-tree'), 'should build valid diff-tree command')
    end)
  end)

  describe('valid queries', function()
    it('should allow valid log with pagination', function()
      local success, qb = pcall(function()
        return GitQueryBuilder(repo):log():paginate(100, 50):file('test.lua')
      end)
      assert(success, 'should build valid query')
      local cmd = qb:to_command()
      assert(cmd:match('log'), 'should contain log')
      assert(cmd:match('-n 100'), 'should contain limit')
      assert(cmd:match('--skip=50'), 'should contain skip')
    end)

    it('should allow valid diff with all options', function()
      local success, qb = pcall(function()
        return GitQueryBuilder(repo):diff():staged():unified(5):file('test.lua')
      end)
      assert(success, 'should build valid query')
      local cmd = qb:to_command()
      assert(cmd:match('diff'), 'should contain diff')
      assert(cmd:match('--staged'), 'should contain staged')
      assert(cmd:match('--unified=5'), 'should contain unified')
    end)

    it('should allow valid stash with subcommand', function()
      local success, qb = pcall(function()
        return GitQueryBuilder(repo):stash():subcommand('list'):paginate(50, 0)
      end)
      assert(success, 'should build valid query')
      local cmd = qb:to_command()
      assert(cmd:match('stash list'), 'should contain stash list')
    end)
  end)
end)
