local test_harness = require('ops.lib.test_harness')
local GitQueryBuilder = require('vgit.git.GitQueryBuilder')

local describe = test_harness.describe
local it = test_harness.it
local eq = test_harness.eq

describe('GitQueryBuilder', function()
  local repo = '/path/to/repo'

  describe('constructor', function()
    it('creates a new query builder', function()
      local qb = GitQueryBuilder(repo)
      eq(qb._repository, repo)
      eq(#qb._args, 0)
    end)
  end)

  describe('log command', function()
    it('builds basic log query', function()
      local qb = GitQueryBuilder(repo):log()
      local args = qb:to_args()
      eq(args[1], '-C')
      eq(args[2], repo)
      eq(args[3], '--no-pager')
      eq(args[4], 'log')
      eq(args[5], '--color=never')
    end)

    it('supports pagination', function()
      local qb = GitQueryBuilder(repo):log():limit(50):skip(100)
      local cmd = qb:to_command()
      assert(cmd:match('-n 50'))
      assert(cmd:match('--skip=100'))
    end)

    it('supports paginate helper', function()
      local qb = GitQueryBuilder(repo):log():paginate(25, 50)
      local cmd = qb:to_command()
      assert(cmd:match('-n 25'))
      assert(cmd:match('--skip=50'))
    end)

    it('supports file filtering', function()
      local qb = GitQueryBuilder(repo):log():file('src/main.lua')
      local args = qb:to_args()
      assert(args[#args - 1] == '--')
      assert(args[#args] == 'src/main.lua')
    end)

    it('supports multiple files', function()
      local qb = GitQueryBuilder(repo):log():files('file1.lua', 'file2.lua')
      local args = qb:to_args()
      assert(args[#args - 2] == '--')
      assert(args[#args - 1] == 'file1.lua')
      assert(args[#args] == 'file2.lua')
    end)

    it('supports custom format', function()
      local qb = GitQueryBuilder(repo):log():pretty('%H %s')
      local cmd = qb:to_command()
      assert(cmd:match('--pretty=format:%%H %%s'))
    end)

    it('chains multiple options', function()
      local qb = GitQueryBuilder(repo):log():limit(100):skip(50):file('test.lua'):pretty('%H')

      local cmd = qb:to_command()
      assert(cmd:match('log'))
      assert(cmd:match('-n 100'))
      assert(cmd:match('--skip=50'))
      assert(cmd:match('test.lua'))
      assert(cmd:match('--pretty=format:%%H'))
    end)
  end)

  describe('show command', function()
    it('builds basic show query', function()
      local qb = GitQueryBuilder(repo):show('HEAD')
      local args = qb:to_args()
      assert(args[3] == 'show')
      assert(args[4] == 'HEAD')
    end)

    it('supports no-patch option', function()
      local qb = GitQueryBuilder(repo):show('abc123'):no_patch()
      local cmd = qb:to_command()
      assert(cmd:match('show'))
      assert(cmd:match('abc123'))
      assert(cmd:match('--no-patch'))
    end)

    it('supports format', function()
      local qb = GitQueryBuilder(repo):show():pretty('%H')
      local cmd = qb:to_command()
      assert(cmd:match('--pretty=format:%%H'))
    end)
  end)

  describe('status command', function()
    it('builds basic status query', function()
      local qb = GitQueryBuilder(repo):status()
      local cmd = qb:to_command()
      assert(cmd:match('status'))
      assert(cmd:match('-u'))
      assert(cmd:match('-s'))
      assert(cmd:match('--no-renames'))
      assert(cmd:match('--ignore-submodules'))
    end)

    it('supports file filtering', function()
      local qb = GitQueryBuilder(repo):status():file('src/')
      local args = qb:to_args()
      assert(args[#args] == 'src/')
    end)
  end)

  describe('diff command', function()
    it('builds basic diff query', function()
      local qb = GitQueryBuilder(repo):diff()
      local cmd = qb:to_command()
      assert(cmd:match('diff'))
      assert(cmd:match('--color=never'))
    end)

    it('supports staged option', function()
      local qb = GitQueryBuilder(repo):diff():staged()
      local cmd = qb:to_command()
      assert(cmd:match('--staged'))
    end)

    it('supports cached option', function()
      local qb = GitQueryBuilder(repo):diff():cached()
      local cmd = qb:to_command()
      assert(cmd:match('--cached'))
    end)

    it('supports unified context', function()
      local qb = GitQueryBuilder(repo):diff():unified(5)
      local cmd = qb:to_command()
      assert(cmd:match('--unified=5'))
    end)

    it('supports refs', function()
      local qb = GitQueryBuilder(repo):diff():refs('HEAD', 'HEAD~1')
      local cmd = qb:to_command()
      assert(cmd:match('HEAD'))
      assert(cmd:match('HEAD~1'))
    end)
  end)

  describe('diff-tree command', function()
    it('builds basic diff-tree query', function()
      local qb = GitQueryBuilder(repo):diff_tree()
      local cmd = qb:to_command()
      assert(cmd:match('diff%-tree'))
      assert(cmd:match('--no-commit-id'))
      assert(cmd:match('--name-status'))
      assert(cmd:match('-r'))
    end)

    it('supports refs', function()
      local qb = GitQueryBuilder(repo):diff_tree():refs('parent', 'commit')
      local cmd = qb:to_command()
      assert(cmd:match('parent'))
      assert(cmd:match('commit'))
    end)
  end)

  describe('blame command', function()
    it('builds basic blame query', function()
      local qb = GitQueryBuilder(repo):blame()
      local cmd = qb:to_command()
      assert(cmd:match('blame'))
      assert(cmd:match('--color=never'))
    end)

    it('supports file', function()
      local qb = GitQueryBuilder(repo):blame():file('src/main.lua')
      local args = qb:to_args()
      assert(args[#args] == 'src/main.lua')
    end)
  end)

  describe('stash command', function()
    it('builds basic stash query', function()
      local qb = GitQueryBuilder(repo):stash()
      local cmd = qb:to_command()
      assert(cmd:match('stash'))
    end)

    it('supports subcommand', function()
      local qb = GitQueryBuilder(repo):stash():subcommand('list')
      local cmd = qb:to_command()
      assert(cmd:match('stash list'))
    end)

    it('supports format with list', function()
      local qb = GitQueryBuilder(repo):stash():subcommand('list'):pretty('%H')
      local cmd = qb:to_command()
      assert(cmd:match('stash list'))
      assert(cmd:match('--pretty=format:%%H'))
    end)
  end)

  describe('generic methods', function()
    it('supports option method', function()
      local qb = GitQueryBuilder(repo):log():option('graph')
      local cmd = qb:to_command()
      assert(cmd:match('--graph'))
    end)

    it('supports option with value', function()
      local qb = GitQueryBuilder(repo):log():option('author', 'John')
      local cmd = qb:to_command()
      assert(cmd:match('--author=John'))
    end)

    it('supports raw_arg', function()
      local qb = GitQueryBuilder(repo):log():raw_arg('--oneline')
      local cmd = qb:to_command()
      assert(cmd:match('--oneline'))
    end)

    it('supports raw_args', function()
      local qb = GitQueryBuilder(repo):log():raw_args('--graph', '--oneline')
      local cmd = qb:to_command()
      assert(cmd:match('--graph'))
      assert(cmd:match('--oneline'))
    end)
  end)

  describe('pagination edge cases', function()
    it('ignores zero limit', function()
      local qb = GitQueryBuilder(repo):log():limit(0)
      local cmd = qb:to_command()
      assert(not cmd:match('-n 0'))
    end)

    it('ignores negative limit', function()
      local qb = GitQueryBuilder(repo):log():limit(-5)
      local cmd = qb:to_command()
      assert(not cmd:match('-n'))
    end)

    it('ignores zero skip', function()
      local qb = GitQueryBuilder(repo):log():skip(0)
      local cmd = qb:to_command()
      assert(not cmd:match('--skip=0'))
    end)

    it('ignores negative skip', function()
      local qb = GitQueryBuilder(repo):log():skip(-10)
      local cmd = qb:to_command()
      assert(not cmd:match('--skip'))
    end)

    it('handles paginate with nil offset', function()
      local qb = GitQueryBuilder(repo):log():paginate(50, nil)
      local cmd = qb:to_command()
      assert(cmd:match('-n 50'))
      assert(not cmd:match('--skip'))
    end)

    it('handles paginate with zero offset', function()
      local qb = GitQueryBuilder(repo):log():paginate(50, 0)
      local cmd = qb:to_command()
      assert(cmd:match('-n 50'))
      assert(not cmd:match('--skip'))
    end)
  end)

  describe('clone', function()
    it('creates independent copy', function()
      local qb1 = GitQueryBuilder(repo):log():limit(50)
      local qb2 = qb1:clone():skip(100)

      local cmd1 = qb1:to_command()
      local cmd2 = qb2:to_command()

      assert(cmd1:match('-n 50'))
      assert(not cmd1:match('--skip'))

      assert(cmd2:match('-n 50'))
      assert(cmd2:match('--skip=100'))
    end)
  end)

  describe('to_command', function()
    it('returns string representation', function()
      local qb = GitQueryBuilder(repo):log():limit(10)
      local cmd = qb:to_command()
      eq(type(cmd), 'string')
      assert(cmd:match('^git '))
    end)
  end)

  describe('complex queries', function()
    it('builds complex log query with all features', function()
      local qb = GitQueryBuilder(repo)
        :log()
        :pretty('%H\x1F%P\x1F%at\x1F%an\x1F%ae\x1F%s')
        :limit(100)
        :skip(200)
        :file('src/main.lua')

      local cmd = qb:to_command()
      assert(cmd:match('log'))
      assert(cmd:match('--pretty=format'))
      assert(cmd:match('-n 100'))
      assert(cmd:match('--skip=200'))
      assert(cmd:match('src/main.lua'))
    end)

    it('builds complex diff query', function()
      local qb = GitQueryBuilder(repo):diff():unified(5):staged():file('test.lua')

      local cmd = qb:to_command()
      assert(cmd:match('diff'))
      assert(cmd:match('--unified=5'))
      assert(cmd:match('--staged'))
      assert(cmd:match('test.lua'))
    end)
  end)
end)
